version: 2.1

jobs:
  UI-Test-homepage:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm ci
            
      - browser-tools/install-chrome
      - node/install-packages 
      - run:
          name: Fix permissions
          command: chmod +x ./node_modules/.bin/nightwatch
      - run:
          name: Run Nightwatch test
          command: npx nightwatch tests/homepageTest.js
      - store_artifacts:
          path: tests_output




  api-tests:
    docker:
      - image: cimg/node:v22.18.0
    steps:
      - checkout
      - run: npm install
      - run: npx mocha mock-user-auth/test/UserAPIs.test.js --reporter mochawesome

workflows:
  version: 2
  run-tests:
    jobs:
      - UI-Test-homepage
      
